from oltl import Id, NonEmptyStringMixIn, TrimmedStringMixIn


class UserId(Id): ...


class UserNameString(NonEmptyStringMixIn, TrimmedStringMixIn): ...


class UrlId(Id): ...


class SessionId(Id): ...


class SelectorId(Id): ...


class XPath(TrimmedStringMixIn, NonEmptyStringMixIn): ...
