from oltl import BaseBytes, Id, NonEmptyStringMixIn, TrimmedStringMixIn


class UserId(Id): ...


class UserNameString(NonEmptyStringMixIn, TrimmedStringMixIn): ...


class SessionId(Id): ...


class SelectorId(Id): ...


class CoreActionId(Id): ...


class WebAgentActionId(Id): ...


class XPath(TrimmedStringMixIn, NonEmptyStringMixIn): ...


class QueryString(TrimmedStringMixIn, NonEmptyStringMixIn): ...


class ElementId(Id): ...


class HtmlSource(TrimmedStringMixIn, NonEmptyStringMixIn): ...


class ImageBinary(BaseBytes): ...


class ClassString(TrimmedStringMixIn, NonEmptyStringMixIn): ...


class ClassSet(set[ClassString]): ...


class TagString(TrimmedStringMixIn, NonEmptyStringMixIn): ...


class DataProcessorId(Id): ...


class DataId(Id): ...
